name: neo
description: NEO-App  This App will be used to control a Controller Device via WiFi. The Controller Device is an external hardware attached to a DSLR Camera with USB Port  App mainly consist of below technical aspects

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0
  flutter_svg: ^0.21.0+1
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  equatable: ^2.0.0
  web_socket_channel: ^2.0.0
  provider: ^5.0.0
  auto_size_text: ^2.1.0
  syncfusion_flutter_charts: ^19.1.69+1
  flutter_hooks: ^0.17.0
  http: ^0.13.3
  visibility_detector: ^0.2.0
  image: ^3.0.2
 # libdsm: ^1.1.8
  flutter_switch: ^0.3.2
  wechat_assets_picker: ^6.0.4 #IOS SETUP
  stacked: ^2.2.5
  url_launcher: ^6.0.9
  image_picker: ^0.8.3+2
  share_plus: ^2.1.4
  path_provider: ^2.0.2
  video_player: ^2.2.0
  cached_network_image: ^3.1.0
  shared_preferences: ^2.0.5 
  #cloud_firestore: ^2.4.0
  chewie: ^1.0.0
  flutter_logs: ^2.1.4
  #firebase_core: ^1.2.0
  #zoomable_image: ^1.3.1
  
  



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons. shared_preferences: ^2.0.5 cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  test: ^1.16.5
  flutter_mjpeg: ^2.0.1
  rxdart: ^0.26.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher/launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/
    - assets/images/gallery/
    - assets/images/localgallery/
    - assets/images/localgallery/IMG_0200.jpg
    - assets/images/flickr/
    - assets/images/flickr/cityscape/
    - assets/images/flickr/landscape/
    - assets/images/flickr/mountain/
    - assets/images/flickr/portrait/
    - assets/images/flickr/seascape/
    - assets/images/flickr/waterfall/
    - assets/images/flickr/undefined/
    - assets/images/waterfall/
    - assets/images/seascape/
    - assets/images/landscape/
    - assets/json/waterfall1.json
    - assets/json/waterfall2.json
    - assets/json/waterfall3.json
    - assets/json/waterfall4.json
    - assets/json/waterfall5.json
    - assets/json/its-landscape_A.json 
    - assets/json/its-landscape_B.json
    - assets/json/its-landscape_C.json
    - assets/json/its-landscape_D.json
    - assets/json/its-landscape_E.json
    - assets/json/seascape_1.json
    - assets/json/seascape_2.json
    - assets/json/seascape_3.json
    - assets/json/seascape_4.json
    - assets/json/seascape_5.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
